### ISSUE TITLE
Get all resources for a challenge is not working

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-challenge-service#1]
Steps to Reproduce
-----------------------------------------------------------------

- Go to GET /challenges/{id}/resources

- Enter id=30048200 (https://www.topcoder-dev.com/challenge-details/30048200/?type=develop)

- Click 'Execute'

- Observe the result

Curl
-----------------------------------------------------------------
``
curl -X GET "https://api.topcoder-dev.com/v3/challenges/30048200/resources" -H "accept: application/json" -H "Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJUb3Bjb2RlciBVc2VyIl0sImlzcyI6Imh0dHBzOi8vYXBpLnRvcGNvZGVyLWRldi5jb20iLCJoYW5kbGUiOiJxYXRlc3R0YyIsImV4cCI6MTUwMjE5MjA3NiwidXNlcklkIjoiNDAxNTM2ODAiLCJpYXQiOjE1MDIxOTE0NzYsImVtYWlsIjoiZGlsaGFuaXRjQHFhLnRlYW0iLCJqdGkiOiJkOWFiMDFmOS01Njk3LTRiZmItODg5Zi1kNTViYTNkYjkyMjQifQ.IPrOuDZOUEDpry8kLdq36BXsr0AxDcBLWO-4g95KSWQ"
``

Actual Result(s)
-----------------------------------------------------------------
``
{
  "id": "string",
  "version": "string",
  "result": [
    {
      "id": 0,
      "projectId": 0,
      "name": "string",
      "role": "string",
      "phaseId": 0,
      "submissions": [
        0
      ],
      "properties": {},
      "createdAt": "2017-08-08T13:30:41.286Z",
      "updatedAt": "2017-08-08T13:30:41.286Z",
      "createdBy": "string",
      "updatedBy": "string"
    }
  ]
}
`` 

Expected Result(s)
-----------------------------------------------------------------
- Must display the resources for a challenge

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.90 (Official Build) (64-bit)

**Comment by skyhit** [comment]
@sdgun not in scope, please check the challenge spec for detail
