### ISSUE TITLE
[Common] No any Updated challenge response displayed

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-challenge-service#10]
Steps to Reproduce
-----------------------------------------------------------------

- Go to PUT /challenges/{id}

- Enter id=30050902 (Wireframe)

- Sample code ``{
  "param": {
    "id": 0,
    "confidentialityType": "string",
    "technologies": [
      {
        "id": 0,
        "name": "string"
      }
    ],
    "subTrack": "WEB_DESIGNS",
    "name": "string",
    "reviewType": "COMMUNITY",
    "billingAccountId": 0,
    "milestoneId": 0,
    "detailedRequirements": "string",
    "submissionGuidelines": "string",
    "registrationStartsAt": "2017-08-09T11:51:48.680Z",
    "registrationEndsAt": "2017-08-09T11:51:48.680Z",
    "checkpointSubmissionStartsAt": "2017-08-09T11:51:48.680Z",
    "checkpointSubmissionEndsAt": "2017-08-09T11:51:48.680Z",
    "submissionEndsAt": "2017-08-09T11:51:48.680Z",
    "round1Info": "string",
    "round2Info": "string",
    "platforms": [
      {
        "id": 0,
        "name": "string"
      }
    ],
    "numberOfCheckpointPrizes": 0,
    "checkpointPrize": 0,
    "finalDeliverableTypes": [
      {
        "id": 0,
        "name": "string"
      }
    ],
    "prizes": [
      0
    ],
    "projectId": 11287,
    "submissionVisibility": false,
    "maxNumOfSubmissions": 0,
    "task": true,
    "assignees": [
      "string"
    ],
    "copilotId": 0,
    "copilotFee": 0,
    "failedRegisterUsers": [
      {
        "handle": "string",
        "reason": "string",
        "properties": [
          {
            "id": 0,
            "title": "string",
            "url": "string"
          }
        ]
      }
    ]
  }
}
``

- Click 'Execute'

- Observe the result

Curl
-----------------------------------------------------------------
``
curl -X PUT "https://api.topcoder-dev.com/v3/challenges/30050902" -H "accept: application/json" -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJUb3Bjb2RlciBVc2VyIl0sImlzcyI6Imh0dHBzOi8vYXBpLnRvcGNvZGVyLWRldi5jb20iLCJoYW5kbGUiOiJxYXRlc3R0YyIsImV4cCI6MTUwMjI3OTgzNSwidXNlcklkIjoiNDAxNTM2ODAiLCJpYXQiOjE1MDIyNzkyMzUsImVtYWlsIjoiZGlsaGFuaXRjQHFhLnRlYW0iLCJqdGkiOiI5NjQ1NmZlYi1jMWZiLTRlZGEtYjViMi1jYjk2ZDI0MmUzZDMifQ.636W7m6_sRG75tP2OdersyEbHx14FfG7yCc2WfxMkQs" -H "content-type: application/json" -d "{ \"param\": { \"id\": 0, \"confidentialityType\": \"string\", \"technologies\": [ { \"id\": 0, \"name\": \"string\" } ], \"subTrack\": \"WEB_DESIGNS\", \"name\": \"string\", \"reviewType\": \"COMMUNITY\", \"billingAccountId\": 0, \"milestoneId\": 0, \"detailedRequirements\": \"string\", \"submissionGuidelines\": \"string\", \"registrationStartsAt\": \"2017-08-09T11:51:48.680Z\", \"registrationEndsAt\": \"2017-08-09T11:51:48.680Z\", \"checkpointSubmissionStartsAt\": \"2017-08-09T11:51:48.680Z\", \"checkpointSubmissionEndsAt\": \"2017-08-09T11:51:48.680Z\", \"submissionEndsAt\": \"2017-08-09T11:51:48.680Z\", \"round1Info\": \"string\", \"round2Info\": \"string\", \"platforms\": [ { \"id\": 0, \"name\": \"string\" } ], \"numberOfCheckpointPrizes\": 0, \"checkpointPrize\": 0, \"finalDeliverableTypes\": [ { \"id\": 0, \"name\": \"string\" } ], \"prizes\": [ 0 ], \"projectId\": 11287, \"submissionVisibility\": false, \"maxNumOfSubmissions\": 0, \"task\": true, \"assignees\": [ \"string\" ], \"copilotId\": 0, \"copilotFee\": 0, \"failedRegisterUsers\": [ { \"handle\": \"string\", \"reason\": \"string\", \"properties\": [ { \"id\": 0, \"title\": \"string\", \"url\": \"string\" } ] } ] }}"
``

Actual Result(s)
-----------------------------------------------------------------
``
{"id":"49482396:15dc20150eb:-78b4","result":{"success":true,"status":400,"content":"You can not switch between studio, software and algorithm after it is saved"},"version":"v3"}
``

Expected Result(s)
-----------------------------------------------------------------
- Must display the correct challenge details.  Check the error code 200 in the documentation below

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.90 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![8](https://user-images.githubusercontent.com/4592712/29119728-f8fd9aa2-7d24-11e7-9a02-a586fca22813.jpg)

**Comment by skyhit** [comment]
@sdgun the update has some limitation, it can not success for any random input.
