### ISSUE TITLE
Correct details for the draft challenge is not populated

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-challenge-service#2]
Steps to Reproduce
-----------------------------------------------------------------

- Do the Api key authorization (https://www.screencast.com/t/tdoCeubXJS   |  https://www.screencast.com/t/zXqCNYXPLcjP )

- Go to PUT /challenges/{id}

- Enter id=30050894 (Newly created challenge from Direct)

- Or Enter id=30049303 (existing challenge in direct) - https://www.topcoder-dev.com/challenge-details/30049303/?type=develop

- Click 'Execute'

- Observe the result

Curl
-----------------------------------------------------------------
Option 01: id=30050894

``
curl -X PUT "https://api.topcoder-dev.com/v3/challenges/30050894" -H "accept: application/json" -H "Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJUb3Bjb2RlciBVc2VyIl0sImlzcyI6Imh0dHBzOi8vYXBpLnRvcGNvZGVyLWRldi5jb20iLCJoYW5kbGUiOiJxYXRlc3R0YyIsImV4cCI6MTUwMjIzNzE3MSwidXNlcklkIjoiNDAxNTM2ODAiLCJpYXQiOjE1MDIyMzY1NzEsImVtYWlsIjoiZGlsaGFuaXRjQHFhLnRlYW0iLCJqdGkiOiJlM2I1ZDM4MC0zZjVjLTRhZmEtYTYwOC1hY2E3NTdmZGYwZDYifQ.Crc3wBhIaXsGp-Kc9PX7E3xBEu1Ed37I6a0HYs9yyPM" -H "content-type: application/json" -d "{ \"param\": { \"id\": 0, \"confidentialityType\": \"string\", \"technologies\": [ { \"id\": 0, \"name\": \"string\" } ], \"subTrack\": \"WEB_DESIGNS\", \"name\": \"string\", \"reviewType\": \"COMMUNITY\", \"billingAccountId\": 0, \"milestoneId\": 0, \"detailedRequirements\": \"string\", \"submissionGuidelines\": \"string\", \"registrationStartsAt\": \"2017-08-09T00:03:50.451Z\", \"registrationEndsAt\": \"2017-08-09T00:03:50.451Z\", \"checkpointSubmissionStartsAt\": \"2017-08-09T00:03:50.451Z\", \"checkpointSubmissionEndsAt\": \"2017-08-09T00:03:50.451Z\", \"submissionEndsAt\": \"2017-08-09T00:03:50.451Z\", \"round1Info\": \"string\", \"round2Info\": \"string\", \"platforms\": [ { \"id\": 0, \"name\": \"string\" } ], \"numberOfCheckpointPrizes\": 0, \"checkpointPrize\": 0, \"finalDeliverableTypes\": [ { \"id\": 0, \"name\": \"string\" } ], \"prizes\": [ 0 ], \"projectId\": 0, \"submissionVisibility\": true, \"maxNumOfSubmissions\": 0, \"task\": true, \"assignees\": [ \"string\" ], \"copilotId\": 0, \"copilotFee\": 0, \"failedRegisterUsers\": [ { \"handle\": \"string\", \"reason\": \"string\", \"properties\": [ { \"id\": 0, \"title\": \"string\", \"url\": \"string\" } ] } ] }}"
``

Option 02: id=30049303

``
curl -X PUT "https://api.topcoder-dev.com/v3/challenges/30049303" -H "accept: application/json" -H "Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJUb3Bjb2RlciBVc2VyIl0sImlzcyI6Imh0dHBzOi8vYXBpLnRvcGNvZGVyLWRldi5jb20iLCJoYW5kbGUiOiJxYXRlc3R0YyIsImV4cCI6MTUwMjIzNzE3MSwidXNlcklkIjoiNDAxNTM2ODAiLCJpYXQiOjE1MDIyMzY1NzEsImVtYWlsIjoiZGlsaGFuaXRjQHFhLnRlYW0iLCJqdGkiOiJlM2I1ZDM4MC0zZjVjLTRhZmEtYTYwOC1hY2E3NTdmZGYwZDYifQ.Crc3wBhIaXsGp-Kc9PX7E3xBEu1Ed37I6a0HYs9yyPM" -H "content-type: application/json" -d "{ \"param\": { \"id\": 0, \"confidentialityType\": \"string\", \"technologies\": [ { \"id\": 0, \"name\": \"string\" } ], \"subTrack\": \"WEB_DESIGNS\", \"name\": \"string\", \"reviewType\": \"COMMUNITY\", \"billingAccountId\": 0, \"milestoneId\": 0, \"detailedRequirements\": \"string\", \"submissionGuidelines\": \"string\", \"registrationStartsAt\": \"2017-08-09T00:03:50.451Z\", \"registrationEndsAt\": \"2017-08-09T00:03:50.451Z\", \"checkpointSubmissionStartsAt\": \"2017-08-09T00:03:50.451Z\", \"checkpointSubmissionEndsAt\": \"2017-08-09T00:03:50.451Z\", \"submissionEndsAt\": \"2017-08-09T00:03:50.451Z\", \"round1Info\": \"string\", \"round2Info\": \"string\", \"platforms\": [ { \"id\": 0, \"name\": \"string\" } ], \"numberOfCheckpointPrizes\": 0, \"checkpointPrize\": 0, \"finalDeliverableTypes\": [ { \"id\": 0, \"name\": \"string\" } ], \"prizes\": [ 0 ], \"projectId\": 0, \"submissionVisibility\": true, \"maxNumOfSubmissions\": 0, \"task\": true, \"assignees\": [ \"string\" ], \"copilotId\": 0, \"copilotFee\": 0, \"failedRegisterUsers\": [ { \"handle\": \"string\", \"reason\": \"string\", \"properties\": [ { \"id\": 0, \"title\": \"string\", \"url\": \"string\" } ] } ] }}"
``

Actual Result(s)
-----------------------------------------------------------------

Option 01: id=30050894

``
{
  "id": "string",
  "version": "string",
  "result": {
    "success": true,
    "status": 0,
    "metadata": {
      "totalCount": 0
    },
    "content": {
      "id": 0,
      "confidentialityType": "string",
      "technologies": [
        {
          "id": 0,
          "name": "string"
        }
      ],
      "subTrack": "WEB_DESIGNS",
      "name": "string",
      "reviewType": "COMMUNITY",
      "billingAccountId": 0,
      "milestoneId": 0,
      "detailedRequirements": "string",
      "submissionGuidelines": "string",
      "registrationStartsAt": "2017-08-09T00:14:28.157Z",
      "registrationEndsAt": "2017-08-09T00:14:28.157Z",
      "checkpointSubmissionStartsAt": "2017-08-09T00:14:28.157Z",
      "checkpointSubmissionEndsAt": "2017-08-09T00:14:28.157Z",
      "submissionEndsAt": "2017-08-09T00:14:28.157Z",
      "round1Info": "string",
      "round2Info": "string",
      "platforms": [
        {
          "id": 0,
          "name": "string"
        }
      ],
      "numberOfCheckpointPrizes": 0,
      "checkpointPrize": 0,
      "finalDeliverableTypes": [
        {
          "id": 0,
          "name": "string"
        }
      ],
      "prizes": [
        0
      ],
      "projectId": 0,
      "submissionVisibility": true,
      "maxNumOfSubmissions": 0,
      "task": true,
      "assignees": [
        "string"
      ],
      "copilotId": 0,
      "copilotFee": 0,
      "failedRegisterUsers": [
        {
          "handle": "string",
          "reason": "string",
          "properties": [
            {
              "id": 0,
              "title": "string",
              "url": "string"
            }
          ]
        }
      ]
    }
  }
}
`` 

Option 02: id=30049303

``
{
  "id": "string",
  "version": "string",
  "result": {
    "success": true,
    "status": 0,
    "metadata": {
      "totalCount": 0
    },
    "content": {
      "id": 0,
      "confidentialityType": "string",
      "technologies": [
        {
          "id": 0,
          "name": "string"
        }
      ],
      "subTrack": "WEB_DESIGNS",
      "name": "string",
      "reviewType": "COMMUNITY",
      "billingAccountId": 0,
      "milestoneId": 0,
      "detailedRequirements": "string",
      "submissionGuidelines": "string",
      "registrationStartsAt": "2017-08-09T01:20:50.506Z",
      "registrationEndsAt": "2017-08-09T01:20:50.506Z",
      "checkpointSubmissionStartsAt": "2017-08-09T01:20:50.506Z",
      "checkpointSubmissionEndsAt": "2017-08-09T01:20:50.506Z",
      "submissionEndsAt": "2017-08-09T01:20:50.506Z",
      "round1Info": "string",
      "round2Info": "string",
      "platforms": [
        {
          "id": 0,
          "name": "string"
        }
      ],
      "numberOfCheckpointPrizes": 0,
      "checkpointPrize": 0,
      "finalDeliverableTypes": [
        {
          "id": 0,
          "name": "string"
        }
      ],
      "prizes": [
        0
      ],
      "projectId": 0,
      "submissionVisibility": true,
      "maxNumOfSubmissions": 0,
      "task": true,
      "assignees": [
        "string"
      ],
      "copilotId": 0,
      "copilotFee": 0,
      "failedRegisterUsers": [
        {
          "handle": "string",
          "reason": "string",
          "properties": [
            {
              "id": 0,
              "title": "string",
              "url": "string"
            }
          ]
        }
      ]
    }
  }
}
``

Expected Result(s)
-----------------------------------------------------------------
- Must display the correct challenge details

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![1 1](https://user-images.githubusercontent.com/4592712/29099980-32a444f4-7cc6-11e7-9bcb-ae085ab8b19d.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.90 (Official Build) (64-bit)

**Comment by sdgun** [comment]
https://www.screencast.com/t/q9UHs1J9e

**Comment by skyhit** [comment]
@sdgun the Authorization is improper, so you are getting the Unauthorized error.
