### ISSUE TITLE
 should tell value of assignees does not exist if the handle does not exist in the system

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/tc-challenge-service#28]
1. create a project and a F2F challenge (id is 30050910 after created)

2. execute the following using command line (or use Swagger UI to fill with necessary parameters):

curl -X PUT "https://api.topcoder-dev.com/v3/challenges/30050910" -H "accept: application/json" -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJUb3Bjb2RlciBVc2VyIl0sImlzcyI6Imh0dHBzOi8vYXBpLnRvcGNvZGVyLWRldi5jb20iLCJoYW5kbGUiOiJ3aW50ZXJmbGFtZTIwMTciLCJleHAiOjE1MDIyODkxOTcsInVzZXJJZCI6IjQwMTUzNzg3IiwiaWF0IjoxNTAyMjg4NTk3LCJlbWFpbCI6InpoZW5nYmluLmRvbmdAZ21haWwuY29tIiwianRpIjoiYTM2YzYwNDMtZWM0MS00ZGU4LThhZDAtMTViOWM5NjZjMmZlIn0.MV6qy2Y7H09vp8DfNE-FgnlGeSCOXq4B0DEjErUHCzY" -H "content-type: application/json" -d "{ \"param\": { \"task\": true, \"assignees\": [ \"doesnotexist\" ], }}"

expected: should tell value of assignees does not exist if the handle does not exist in the system

actual: see screenshots, just a simple message “A syntax error has occurred.”

Input:
<img width="428" alt="a1" src="https://user-images.githubusercontent.com/4590317/29126959-4b8c8116-7d52-11e7-86c7-55c8e6d69441.png">

Output:

<img width="1325" alt="b1" src="https://user-images.githubusercontent.com/4590317/29127090-acdb300c-7d52-11e7-93ef-82680dbe18e6.png">

**Comment by skyhit** [comment]
@winterflame your body request is not valid json, additional `,`
