### ISSUE TITLE
'Bad Request' displayed when user perform operation after entering challenges id

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-challenge-service#4]
Steps to Reproduce
-----------------------------------------------------------------

- Do the Api key authorization (https://www.screencast.com/t/tdoCeubXJS   |  https://www.screencast.com/t/zXqCNYXPLcjP )

- Go to PUT /challenges/{id}

- Enter id=30050894  (Newly created challenge from Direct)

- Click 'Execute'

- Observe the result

Curl
-----------------------------------------------------------------
``
curl -X PUT "https://api.topcoder-dev.com/v3/challenges/30050894" -H "accept: application/json" -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJUb3Bjb2RlciBVc2VyIl0sImlzcyI6Imh0dHBzOi8vYXBpLnRvcGNvZGVyLWRldi5jb20iLCJoYW5kbGUiOiJxYXRlc3R0YyIsImV4cCI6MTUwMjI2OTAxMywidXNlcklkIjoiNDAxNTM2ODAiLCJpYXQiOjE1MDIyNjg0MTMsImVtYWlsIjoiZGlsaGFuaXRjQHFhLnRlYW0iLCJqdGkiOiJhNGM0NTUyYS1kNTJmLTRhNmQtYTI5Yy0zNGM4ZGFjMWYzYzgifQ.oJYiD_Ey7pkaQytCLORPFxXOqZZ59NAJZzKFrvQNzlc" -H "content-type: application/json" -d "{ \"param\": { \"id\": 0, \"confidentialityType\": \"string\", \"technologies\": [ { \"id\": 0, \"name\": \"string\" } ], \"subTrack\": \"WEB_DESIGNS\", \"name\": \"string\", \"reviewType\": \"COMMUNITY\", \"billingAccountId\": 0, \"milestoneId\": 0, \"detailedRequirements\": \"string\", \"submissionGuidelines\": \"string\", \"registrationStartsAt\": \"2017-08-09T08:47:35.034Z\", \"registrationEndsAt\": \"2017-08-09T08:47:35.034Z\", \"checkpointSubmissionStartsAt\": \"2017-08-09T08:47:35.034Z\", \"checkpointSubmissionEndsAt\": \"2017-08-09T08:47:35.034Z\", \"submissionEndsAt\": \"2017-08-09T08:47:35.034Z\", \"round1Info\": \"string\", \"round2Info\": \"string\", \"platforms\": [ { \"id\": 0, \"name\": \"string\" } ], \"numberOfCheckpointPrizes\": 0, \"checkpointPrize\": 0, \"finalDeliverableTypes\": [ { \"id\": 0, \"name\": \"string\" } ], \"prizes\": [ 0 ], \"projectId\": 0, \"submissionVisibility\": true, \"maxNumOfSubmissions\": 0, \"task\": true, \"assignees\": [ \"string\" ], \"copilotId\": 0, \"copilotFee\": 0, \"failedRegisterUsers\": [ { \"handle\": \"string\", \"reason\": \"string\", \"properties\": [ { \"id\": 0, \"title\": \"string\", \"url\": \"string\" } ] } ] }}"
``

Actual Result(s)
-----------------------------------------------------------------
``
{"id":"49482396:15dc20150eb:-7a82","result":{"success":true,"status":400,"content":"You can not switch between studio, software and algorithm after it is saved"},"version":"v3"}
`` 

Expected Result(s)
-----------------------------------------------------------------
- Must display the correct challenge details

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.90 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![2](https://user-images.githubusercontent.com/4592712/29113475-b81dabf0-7d0e-11e7-906b-5116a2633801.jpg)

**Comment by sdgun** [comment]
https://www.screencast.com/t/2ozmggFk33

**Comment by skyhit** [comment]
@sdgun this is actually a proper message, our system has the limitation that you can not freely switch the `SubTrack` when updating a challenge.
