### ISSUE TITLE
""Only F2F and Design F2F support private tasks"" displayed when user search for 'Web Design' challenges id

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-challenge-service#8]
Steps to Reproduce
-----------------------------------------------------------------

- Do the Api key authorization (https://www.screencast.com/t/tdoCeubXJS   |  https://www.screencast.com/t/zXqCNYXPLcjP )

- Go to PUT /challenges/{id}

- Enter id=30050905 

- Click 'Execute'

- Observe the result

Curl
-----------------------------------------------------------------
``
curl -X PUT "https://api.topcoder-dev.com/v3/challenges/30050905" -H "accept: application/json" -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJUb3Bjb2RlciBVc2VyIl0sImlzcyI6Imh0dHBzOi8vYXBpLnRvcGNvZGVyLWRldi5jb20iLCJoYW5kbGUiOiJxYXRlc3R0YyIsImV4cCI6MTUwMjI3Mjg1NCwidXNlcklkIjoiNDAxNTM2ODAiLCJpYXQiOjE1MDIyNzIyNTQsImVtYWlsIjoiZGlsaGFuaXRjQHFhLnRlYW0iLCJqdGkiOiJiNzhkNWY4ZS02NDQ1LTQ1ZmYtOTRhYi1kZDhkYTQ0ZmIxYzQifQ.XQgAKN_D2JAGRB5ROrhlxkgHPums1fdZK-xMdcCX-Cc" -H "content-type: application/json" -d "{ \"param\": { \"id\": 0, \"confidentialityType\": \"string\", \"technologies\": [ { \"id\": 0, \"name\": \"string\" } ], \"subTrack\": \"WEB_DESIGNS\", \"name\": \"string\", \"reviewType\": \"COMMUNITY\", \"billingAccountId\": 0, \"milestoneId\": 0, \"detailedRequirements\": \"string\", \"submissionGuidelines\": \"string\", \"registrationStartsAt\": \"2017-08-09T09:51:30.053Z\", \"registrationEndsAt\": \"2017-08-09T09:51:30.053Z\", \"checkpointSubmissionStartsAt\": \"2017-08-09T09:51:30.053Z\", \"checkpointSubmissionEndsAt\": \"2017-08-09T09:51:30.053Z\", \"submissionEndsAt\": \"2017-08-09T09:51:30.053Z\", \"round1Info\": \"string\", \"round2Info\": \"string\", \"platforms\": [ { \"id\": 0, \"name\": \"string\" } ], \"numberOfCheckpointPrizes\": 0, \"checkpointPrize\": 0, \"finalDeliverableTypes\": [ { \"id\": 0, \"name\": \"string\" } ], \"prizes\": [ 0 ], \"projectId\": 0, \"submissionVisibility\": true, \"maxNumOfSubmissions\": 0, \"task\": true, \"assignees\": [ \"string\" ], \"copilotId\": 0, \"copilotFee\": 0, \"failedRegisterUsers\": [ { \"handle\": \"string\", \"reason\": \"string\", \"properties\": [ { \"id\": 0, \"title\": \"string\", \"url\": \"string\" } ] } ] }}"``

Actual Result(s)
-----------------------------------------------------------------
``
{"id":"49482396:15dc20150eb:-793c","result":{"success":true,"status":400,"content":"Only F2F and Design F2F support private tasks"},"version":"v3"}
`` 

Expected Result(s)
-----------------------------------------------------------------
- Must execute the PUT action and display the correct output

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.90 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![5](https://user-images.githubusercontent.com/4592712/29115983-13e4f4ea-7d17-11e7-98c1-24d8c6b6ab6b.jpg)

**Comment by sdgun** [comment]
https://www.screencast.com/t/2ozmggFk33

**Comment by skyhit** [comment]
@sdgun this is correct, the task field is only applied to F2F and Design F2F.
